### PR TITLE
Update to 0.12.5

### PR DESCRIPTION
**Pull request by hafen**

### CODE REVIEW

**Comment by bryevdv** [comment]
Just as an FYI, `0.12.6` will hopefully be Tuesday (and hopefully not much work for you)

**Comment by elbamos** [comment]
It would be great if this could be merged - we're about to use it in production.

**Comment by bryevdv** [comment]
ping @hafen  any thoughts?

**Comment by elbamos** [comment]
@hafen Yes, I'm using this at the moment, because I'm embedding the output in a larger app that has js library conflicts with the earlier version.  It would be really great if you could release this.  Also - would be even greater if you could include support for clickable legends :)  See https://bokeh.pydata.org/en/latest/docs/user_guide/interaction/legends.html

**Comment by bryevdv** [comment]
Just FYI 1.0 dev builds are out and I plan to cut a 1.0 rc on the 15th

**Comment by bryevdv** [comment]
@hafen noticed the new activity, is there anything I can help with? FYI we plan to release 2.1 next week-ish so if there are new project URLs that we should update in the docs or anything, please lmk

**Comment by hafen** [comment]
Thanks for checking. These are incremental updates to an older version of the package (the one published to CRAN) that address some immediate issues that would otherwise prohibit it from remaining on CRAN. There's still work to do on the redesigned package to be up to date with the latest bokeh release as well as ensuring backwards compatibility with the R interface before I can publish that to CRAN. If you'd like to discuss this offline some time, let me know.

**Comment by bryevdv** [comment]
@hafen FYI we plan to change the `master` branch name to `main` very soon, that process will close existing PRs. Is there something we should wait on or should we proceed and let PRs be re-opened again later?

**Comment by bryevdv** [comment]
Just an FYI that I will carry out the rename tonight, which will close this PR automatically (but it can be re-opened agains `main`)

**Comment by hafen** [comment]
@bryevdv sorry for the delay. Feel free to carry out the rename and we can re-open PRs as necessary.

**Pull request closed without merging**
