### PR TITLE
Axis tick formatter

### PR DESCRIPTION
**Pull request by jrowen**
This is an attempt at enhancing the `x_axis` and `y_axis` functions to also support [axis tick formatting](http://bokeh.pydata.org/en/latest/docs/reference/models.html#bokeh-models-formatters).  Please let me know if you have any feedback or suggestions.

For the datetime axis, I had used `jsonlite` to create a parameter dictionary that was understandable to rbokeh.  Below is an example of the desired output (from `jsonlite`) and the `RJSONIO` output.  I'd be happy to switch to `RJSONIO` if that's the desired approach and there's a way to mimic the `jsonlite` output.
```
> jsonlite::toJSON(list(days="%d", months="%b"))
{"days":["%d"],"months":["%b"]} 
> RJSONIO::toJSON(list(days="%d", months="%b"))
[1] "{\n \"days\": \"%d\",\n\"months\": \"%b\" \n}" 
```

Here are some examples of the new functionality, which have also been included updated function documentation.
```
# Disable scientific tick labels
figure() %>%
  ly_points(rnorm(10), rnorm(10) / 1000) %>%
  y_axis(use_scientific = FALSE)

# Specify datetime tick labels; the appropriate datetime units are automatically
#   chosen
figure() %>%
  ly_lines(seq(as.Date("2012-01-01"),as.Date("2012-12-31"), by="days"), 
           rnorm(366)) %>%
  x_axis(label = "Date", formats = list(months="%b-%Y", days="%d"))
figure() %>%
  ly_lines(seq(as.Date("2012-01-01"),as.Date("2012-02-01"), by="days"), 
           rnorm(32)) %>%
  x_axis(label = "Date", formats = list(months="%b-%Y", days="%d"))

# Specify numeric tick labels
figure() %>%
  ly_points(rnorm(10), rnorm(10) * 10000) %>%
  y_axis(number_formatter = "numeral", format = "0,000")

figure() %>%
  ly_points(rnorm(10), rnorm(10) * 100) %>%
  y_axis(number_formatter = "printf", format = "%0.1f%%")
```

### CODE REVIEW

**Comment by hafen** [comment]
This looks great!!  Thanks.  Everything looks good.  Just a few quick things:

This is a big enough contribution that you should add yourself as a contributor in DESCRIPTION.  If there are other features you need, please feel free to post an issue, discuss, and continue to contribute!

Could you take the new examples in `man-roxygen/ex-axis.R` and stick them in `tests/testthat/test-figures.R`?  If you store the result as an object and call `print_model_json` on the object as you see in the other tests, this simulates the process of doing the final json preparation before sending to the web, but doesn't make a window open up with the plot, which can be annoying for tests.

Also in `R/helpers_extra_pars.R` could you add 

```
#' @importFrom jsonlite toJSON
```

and re-run roxygen?

Finally, we should bump the version to 0.2.3 and add a line in NEWS.md about the new feature.

Oh also about jsonlite I much prefer jsonlite.  When this package started htmlwidgets was using RJSONIO but of course has since switched, so keeping everything jsonlite is good.

**Comment by jrowen** [comment]
I wasn't sure if I should update `NAMESPACE` for jsonlite.  I'm using `jsonlite::toJSON`, so I don't think the update is required, and I was concerned adding `importFrom(jsonlite, toJSON)` would conflict with the existing `importFrom(RJSONIO, toJSON)`.

**Comment by hafen** [comment]
Good point.  Even using `jsonlite::`, we still need to import to properly pass R CMD check.  I forgot about the RJSONIO imports - looking at the code they could be replaced with jsonlite.  Let me look into that quickly and do some testing and I'll update master.

**Comment by hafen** [comment]
I've removed RJSONIO dependencies.  Could you please merge https://github.com/hafen/rbokeh/ into this PR?

**Comment by jrowen** [comment]
I think this is all set.  Let me know if you run into any issues or have additional suggestions.  Thanks for handling `jsonlite`.

**Comment by hafen** [comment]
Looks great.  Thanks!

**Pull request merged**
