### PR TITLE
Fix minor typos in docs

### PR DESCRIPTION
**Pull request by jameslamb**
Thank you for this awesome package! I noticed some tiny mistakes in the documentation today. Please consider this PR to fix them.

### CODE REVIEW

**Comment by jameslamb** [comment]
@hafen was looking at my open PRs tonight and realized this one has been out there for a while. Could it be merged?

**Comment by bryevdv** [comment]
@hafen can this be merged? upcoming branch name switch from `master` to `main` will close this otherwise.

**Comment by jameslamb** [comment]
it's just typo fixes and this PR has almost reached its third birthday...if it's easier for you folks to just close it, I'm ok with it.

**Comment by bryevdv** [comment]
OK I am going to go ahead and close, since the branch rename would do it automatically anyway. I do hope we can jumpstart dev on this project more in the near future.

**Comment by jameslamb** [comment]
I hope so! I teach an "Intro to R" course at Marquette University and I recently removed `{rbokeh}` from my list of recommended dataviz packages because I thought it was abandoned.

**Comment by hafen** [comment]
@jameslamb I apologize for being so slow on this, and thanks for contributing to the package. My ability to contribute to open source has been greatly diminished over the last few years. @bryevdv I agree that hopefully we can revive work on this project!

**Pull request closed without merging**
