### PR TITLE
Replaces do.call's in ly_boxplot with explicit function calls.

### PR DESCRIPTION
**Pull request by lianos**
This is a fix for Issue #173.

Creating a boxplot with the simulated code there takes ~ 2.5s with the current multiple-do.call implementation. This patch reduces the time down to to ~ 0.15s

```r
xdat <- data.frame(
  group=rep('bg', 20000),
  score=rnorm(20000),
  stringsAsFactors=FALSE)
idx <- sample(nrow(xdat), 50)
xdat$group[idx] <- 'fg'
xdat$score[idx] <- rnorm(length(idx), 0.75)

system.time(p <- figure(xdat) %>% ly_boxplot(x=group, y=score))
##    user  system elapsed
##   0.139   0.004   0.146
```

Unfortunately not using `do.call` can be quite a bit less convenient, but I think the speed gains here are probably worth it.

### CODE REVIEW

**Comment by hafen** [comment]
Thanks for the PR!  I was noticing that boxplot was pretty slow today.  The purpose for the do.call was that depending on how the parameters are specified (there are many ways to specify things), you can't be quite sure which parameters will be passed on to `ly_crect()`.  I'll need to think over a few scenarios to make sure every case is covered, but I think this will be good.

**Comment by hafen** [comment]
Can you merge into the dev branch?  I'm getting everything for the next CRAN release staged there.

Also, to stay consistent with the style of the rest of the code, can you use things like `args$params$visible` instead of `args[['params']][['visible']]` (actually with new lintr tests the latter wouldn't pass).

**Comment by lianos** [comment]
Sure -- will update the coding style.

I originally had it the `$` way and surprised to learn that lintr prefers the `$` since I thought (assumed) the `list[['x']]` style was the preferred "pedantic" style over `list$x` due to the partial completion that `$` allows ...

**Comment by jrounds** [comment]
http://stackoverflow.com/questions/13923301/is-there-a-work-around-for-slow-performance-of-do-callcbind-xts-in-r-2-15

You inspired me to learn more about R.  This was an interesting scenario.

**Comment by lianos** [comment]
Yeah, I stumbled onto that when trying different approaches.

I tried using `quote=TRUE`, but it didn't seem to help in this scenario -- you can try if you like, though.

The `do.call` bites a lot of folks -- I think most notorious is the `do.call(rbind, list.of.data.frames)` idiom, when people want to stack many data.frames on top of each other.

It's slowness has lead to many different implementations to do that much quicker, eg. dplyr's `bind_rows` and data.table's `rbindlist` ...

**Comment by hafen** [comment]
Oops maybe lintr does prefer the pedantic style - I'm not an expert there.  But `$` is good.

@jrounds good to see you on here.  Yeah I've experienced the fun of do.call with large lists of arguments but wouldn't have thought it would be an issue in this case.

**Pull request closed without merging**
